version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "3000:80"
    volumes:
      - ./back-end/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  nodejs:
    build: .
    image: dongquannguyen/nodejs
    environment:
      - PORT=3000
    depends_on:
      - mongo

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=quan
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
    # ports:
    #   - "27018:27017"
    volumes:
      - mongo-db:/data/db

volumes:
  mongo-db: